name: "Chore"
description: Track build process or auxiliary tool changes.
title: "chore(scope): <title>"
labels: ["chore"]
body:
  - type: textarea
    id: task
    attributes:
      label: Task Description
      description: Describe the maintenance task or tooling change.
      placeholder: e.g. Update Dockerfile base image, upgrade dependencies...
    validations:
      required: true
