name: "Documentation"
description: Propose documentation updates or additions.
title: "docs(scope): <title>"
labels: ["documentation"]
body:
  - type: textarea
    id: target
    attributes:
      label: Description
      description: Describe what documentation needs to be updated or created.
      placeholder: e.g. Update the installation guide in README...
    validations:
      required: true
