name: "Feature Request"
description: Standardized template for RevieU features with User Stories and Checklists.
title: "feat(scope): <title>"
labels: ["feat"]
body:
  - type: markdown
    attributes:
      value: |
        ### RevieU Development Specification
        Ensure all architectural requirements are addressed. 
        **Note: Priority must be managed directly in the GitHub Project board.**

  - type: textarea
    id: user-story
    attributes:
      label: 1. User Story
      description: Describe the requirement from the user's perspective.
      placeholder: |
        - AS A [user type/role]
        - I WANT TO [perform some action]
        - SO THAT [some value or benefit is achieved]
    validations:
      required: true

  - type: textarea
    id: tech-specs
    attributes:
      label: 2. Technical Specifications
      description: Architecture design, database schema, or infra requirements.
      placeholder: |
        - API Endpoint: [METHOD] /path
        - Database: Schema migrations or new fields
        - Infrastructure: Env vars, Redis, S3, or other dependencies
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 3. Acceptance Criteria
      description: Use Given/When/Then format to define success.
      placeholder: |
        - Given: [pre-condition]
        - When: [action]
        - Then: [expected result]
    validations:
      required: true

  - type: checkboxes
    id: implementation-checklist
    attributes:
      label: 4. Implementation Checklist
      description: Tasks that must be completed during development.
      options:
        - label: Setup project structure and boilerplate
        - label: Implement core business logic
        - label: Create/Update database migrations
        - label: Integrate third-party services (if applicable)
        - label: Perform self-review of code logic

  - type: checkboxes
    id: dod
    attributes:
      label: 5. Definition of Done (DoD)
      description: Final requirements for closing the issue.
      options:
        - label: Unit tests passed with >80% coverage
        - label: Security hardening completed (Input validation/Rate limiting)
        - label: API documentation updated (Swagger/Postman)
        - label: Integration tested in Dev environment
        - label: Code review approved by Tech Lead

  - type: textarea
    id: resources
    attributes:
      label: 6. Resources
      description: Figma designs, documentation, or related issues.
      placeholder: "Figma Link: https://..."
