name: "Performance Improvement"
description: Report a performance issue or suggest an optimization.
title: "perf(scope): <title>"
labels: ["performance"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Performance Bottleneck
      description: Describe the current performance issue.
      placeholder: e.g. Home page load time is too long, SQL query missing index...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Optimization
      description: What optimization approach do you suggest?
    validations:
      required: true
