name: "Refactor / Tech Debt"
description: Track code refactoring, dependency upgrades, or tech debt cleanup.
title: "refactor(scope): <title>"
labels: ["maintenance", "internal"]
body:
  - type: textarea
    id: target
    attributes:
      label: Target Module/File
      description: Which part of the code needs refactoring?
      placeholder: src/components/Auth.tsx
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason for Refactoring
      description: Why does this need to change? (e.g. performance, maintainability, outdated dependency)
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Approach
      description: If you have a refactoring strategy in mind, describe it here.
