name: "Style"
description: Propose formatting changes that do not affect logic.
title: "style(scope): <title>"
labels: ["style"]
body:
  - type: textarea
    id: details
    attributes:
      label: Description
      description: Describe the formatting changes needed.
      placeholder: e.g. Enforce 2-space indentation, fix Prettier errors...
    validations:
      required: true
