name: "Test"
description: Add missing tests or correct existing tests.
title: "test(scope): <title>"
labels: ["testing"]
body:
  - type: textarea
    id: scope
    attributes:
      label: Test Scope
      description: What functionality needs test coverage?
      placeholder: e.g. Add unit tests for the Auth module...
    validations:
      required: true
